name: Build luncheonOS image

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: archlinux
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Remember: access using $GITHUB_WORKSPACE

      - name: Initialize build environment
        run: |
          pacman -Syu archiso
          mkdir workingdir
          mkdir builddir

      - name: Build image with `mkarchiso`
        run: mkarchiso -v -w workingdir -o builddir $GITHUB_WORKSPACE
          
      - name: Artifact resulting ISO for one day
        uses: actions/upload-artifact@v3
        with:
        #FIXME: Learn to actually use the GitHub artifaction system
          name: my-iso
          path: builddir
          retention-days: 1
